@startuml 5. Verificar cuenta empresa
actor Encargado_de_contabilidad


Encargado_de_contabilidad -- (Gestionar cuenta empresa)

(Gestionar cuenta empresa) -.> (Verificar cuenta empresa): <<Include>>
(Gestionar cuenta empresa) -.> (Verificar banco): <<Include>>



@enduml