@startuml 1er Nivel Alto Nivel


package Paquete_RRHH {
 
  [RRHH]
}
package Contabilidad {
 
  [Contabilidad.]
}
package Facturación {
 
  [Facturación.]
}




[Contabilidad.] .-left->[RRHH] :"Acceso"
[Facturación.] .-up->[RRHH] :"Acceso"
[Contabilidad.] .-down-> [Facturación.]:"Acceso"


@enduml