@startuml 10. Gestionar Banco

actor Encargado_de_contabilidad


Encargado_de_contabilidad -> ":FormBanco": IntroduceInformación(Banco)



":FormBanco" -> "Controlador Banco": VerificaInformación(Banco)


"Controlador Banco" -> "Banco": VerificaBanco(Banco)

"Banco"--> ":FormBanco" : BancoNoExiste():No Existe

Encargado_de_contabilidad -> ":FormBanco": GuardarBanco() 
":FormBanco" -> "Controlador Banco": GuardarBanco() 

"Controlador Banco" -> "Banco": Registrar(Banco)

"Banco"--> ":FormBanco" : BancoCreado()




@enduml