@startuml 2. Gestionar RRHH

actor Encargado_RRHH


Encargado_RRHH -> ":FormCliente": Introducir(Empleado, Cargo)

Encargado_RRHH -> ":FormCliente": Guardar(Empleado) 

":FormCliente" -> "Control empleado": Verificar(Empleado, Cargo)
":FormCliente" -> "Control empleado": Guardar(Empleado)

"Control empleado" -> "Empleado": Verificar(Empleado)

"Control empleado" -> "Empleado": Registrar(Empleado)

"Empleado" -> "Cargo": Verificar(Cargo)


"Empleado"--> ":FormCliente":Empleado registrado




@enduml