@startuml 3. Balancear facturas y depositos

actor Encargado_de_contabilidad


Encargado_de_contabilidad -> ":FormBalanceo":Balancear


":FormBalanceo" -> "Control balancear": Balancear()
"Control balancear" -> "Mensajero":BuscarMensajero(Mensajero)
"Control balancear" -> "Facturas": BuscarFacturas(Facturas)
"Control balancear" -> "Facturas": SumarFacturas()
"Control balancear" -> "Planillas": BuscarPlanillas(Mensajero)
"Control balancear" -> "Planillas": SumarDepositos()
"Control balancear" -> "CuentaEmpresa": BuscarCuentaEmpresa(Banco)
"Control balancear" -> "Cliente": BuscarCliente(Factura)
"Control balancear" -> "CuentaCliente": BuscarCuentaCliente(Cliente)
"Control balancear" -> "CuentaEmpresa": DebitarCuentaEmpresa(CuentaEmpresa, Banco)
"Control balancear" -> "CuentaCliente": AcreditarCuentaCliente(CuentaCliente)







@enduml