@startuml 8. Elaborar informe de balanceoCorregido

actor Encargado_de_contabilidad


Encargado_de_contabilidad -> ":Reporte" : Introduce fecha


":Reporte" -> ":Controladora reporte": BuscaInformación(Mensajero)
":Reporte" -> ":Controladora reporte": BuscaFacturas(Mensajero)

":Controladora reporte" -> "Mensajero": Buscar mensajero
":Controladora reporte" -> "Facturas": Buscar facturas
":Controladora reporte" --> ":Controladora reporte": Devolver Monto factura

":Controladora reporte" -> "Planillas": Buscar planillas
":Controladora reporte" --> ":Controladora reporte": Devolver Monto planilla

":Controladora reporte"-> "Cuenta empresa" : Buscar cuenta empresa
":Controladora reporte" -> "Banco": Buscar banco

":Controladora reporte" --> ":Reporte" : Reporte balanceo


@enduml