@startuml 8. Elaborar informe de balanceoCorregido

actor Encargado_de_contabilidad


Encargado_de_contabilidad -> ":Reporte" 


":Reporte" -> ":Mensajero": BuscaInformación(Mensajero)
":Reporte" -> ":Mensajero": BuscaFacturas(Mensajero)


":Mensajero" -> "Controlador de Balanceo": Envia Facturas e información del mensajero

"Controlador de Balanceo" -> "Facturas":Se suman todas las facturas
"Facturas" -> "Plantillas":Busca todas las plantillas
"Facturas" -> "Plantillas":Se suman todas las plantillas

"Plantillas" -> "Controlador de Balanceo":Verifica el sumatorio de todas las facturas
"Controlador de Balanceo" -> ":Reporte": Si son iguales se balancea




@enduml