@startuml Paquete clases  Facturacion





folder "Paquete Facturacion" {

class Factura {
  String nroFactura
  Date fecha
  long int Monto_Factura

  {abstract} bool Buscar(nroFactura): return Encontrado
  {abstract} void Registrar(Factura) 
  {abstract} void Modificar(Factura) 
  {abstract} void Eliminar(Factura)
}

class DetalleFactura {
  Float cantidad
  Float precio

  {abstract} bool Buscar(CodProducto): return Encontrado
  {abstract} bool Buscar(nroFactura): return Encontrado
  {abstract} bool Buscar(Factura, Producto): return Encontrado
  {abstract} void Registrar(Factura) 
  {abstract} void Modificar(Factura) 
  {abstract} void Eliminar(Factura)
}
class Cliente {
  String codCliente
  String nombre
  String apellido
  String CI
  String dirección
  long int NIT 
  String Nombre Nit
  String teléfono

  {abstract} bool Buscar(codCliente): return Encontrado
  {abstract} void Registrar(Cliente) 
  {abstract} void Modificar(Cliente) 
  {abstract} void Eliminar(Cliente)
}

class Productos {
  String nombre
  String apellido
  long int precio
  float cantidadExistencia

  {abstract} bool Buscar(codProducto): return Encontrado
  {abstract} void Registrar(Producto) 
  {abstract} void Modificar(Producto) 
  {abstract} void Eliminar(Producto)
}





Cliente "1" -left- "0..*" Factura

Factura "1..*" -down- "0..*" Productos

Factura "0..*" -up- "1..*" RRHH::Empleados

Cliente "1" -right- "1..* " Contabilidad::CuentaCliente

(Factura, Productos) .. DetalleFactura



  }






@endluml